version: '3'
services:
  php-fpm: 
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php-fpm
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  nginx:
    image: nginx:1.21-alpine
    container_name: server-nginx
    volumes: 
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
    networks:
      - app-network

  react:
    build:
      context: .
      dockerfile: npm.dockerfile
    container_name: react
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    container_name: db-postgres
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge